# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Principal Software Engineer
author: Jason Walker
logo: logo.png

# Auto-exclude files not in the toc
only_build_toc_files: true
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", ".venv"]

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: resume.tex

parse:
  myst_enable_extensions:
    - colon_fence
    - substitution

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    language: en
    html_show_copyright: false

# Information about where the book exists on the web
repository:
  url: https://github.com/ungood/ungood.github.com # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_edit_page_button: false
  use_issues_button: false
  extra_navbar: ""
  extra_footer: ""
  baseurl: "https://onetrue.name"
  google_analytics_id: "G-ZYTNS5GN7G"
  